# Generated by Django 5.1.4 on 2025-01-17 21:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatsPrisEnCharge', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Filtrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteres', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('motDePasse', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='medecins', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='medecins', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('idenreg', models.AutoField(primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=200)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('naissance', models.DateField()),
                ('admission', models.DateTimeField(default=datetime.datetime.now)),
                ('medication', models.TextField()),
                ('notes', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.medecin')),
            ],
        ),
    ]
