# Generated by Django 5.1.4 on 2025-01-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='motDePasse',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
