# Generated by Django 5.1.4 on 2025-01-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('medico', '0002_remove_medecin_groups_remove_medecin_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='medecin_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='motDePasse',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='medecin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='medecin_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
